### ISSUE TITLE
Very slow loading when adding widget to homescreen

### ISSUE THREAD

**Issue by FriederHannenheim** [spaceapi-community/my-hackerspace#23]
When I try to create a widget the app shows loading. I can tap the loading icon away but can't choose a hackerspace.

**Comment by niccokunzmann** [comment]
Could you say what you would like to see happening instead?
I found that if I waited, the widget fills up.

**Comment by FriederHannenheim** [comment]
Also the app crashes when I click ok to add the widget. I'm on Lawnchair 12.1.0

**Comment by FriederHannenheim** [comment]
Alright this has sparked my interest. Working on a fix

**Comment by niccokunzmann** [comment]
Hm. This looks like several issues. Can you make a list for clarity?

**Comment by dbrgn** [comment]
Can confirm that loading seems to be very slow. If someone could debug (and maybe fix) the loading behavior, that would be very welcome.

**Comment by niccokunzmann** [comment]
Hm. I was looking at Widget.java, line 303.

https://github.com/spaceapi-community/my-hackerspace/blob/a05089e381e6167def804611975bd40a7ee4bae9/app/src/main/java/io/spaceapi/community/myhackerspace/Widget.java#L303

This appeared a while AFTER the widget was created. It seems that the UpdateService

https://github.com/spaceapi-community/my-hackerspace/blob/cd8e02d71651b2e31a2dbdbb3af00b43e4a53e69/app/src/main/java/io/spaceapi/community/myhackerspace/Widget.java#L287

is not used until it is triggered by some event.

In the AndroidManifest.xml we have this:

https://github.com/spaceapi-community/my-hackerspace/blob/cd8e02d71651b2e31a2dbdbb3af00b43e4a53e69/app/src/main/AndroidManifest.xml#L76

As well as the different `receiver -> intent-filter`:

- https://github.com/spaceapi-community/my-hackerspace/blob/cd8e02d71651b2e31a2dbdbb3af00b43e4a53e69/app/src/main/AndroidManifest.xml#L64
- https://github.com/spaceapi-community/my-hackerspace/blob/cd8e02d71651b2e31a2dbdbb3af00b43e4a53e69/app/src/main/AndroidManifest.xml#L68

My guess is that these trigger the update service. When the widget is first created, this does not take place.

Here is the update mechanism:

https://github.com/spaceapi-community/my-hackerspace/blob/cd8e02d71651b2e31a2dbdbb3af00b43e4a53e69/app/src/main/java/io/spaceapi/community/myhackerspace/Widget.java#L305

I would guess that once the widget is successfully created either

- The activity that creates it (probably closed by then) can notify the widget internally inside the app
- There is a receiver on creation of the widget that can be triggered.

## ... Researching ....

**Comment by niccokunzmann** [comment]
It seems to me that Widget_config calls updateAlarm and that creates the system alarm for update with a 50ms delay. This is but a rough estimation and might go wrong - it might not be updated after 50ms. That might be the problem here.

So, I had a look and I add the direct update without the redirection through the Android operating system...
And it is there! Instantly....

PR in progress...

**Comment by dbrgn** [comment]
When adding the widget, the list of spaces needs to be loaded (in order to choose a space). Sometimes this is still slow, but there is an issue with loading of the directory that I'm currently investigating. It's probably an IPv6 issue on the directory server (which sometimes runs into a timeout, causing a 30-60 loading time).

However, the main issue was probably resolved with #34, so we can probably close this.
