### ISSUE TITLE
No merges, should I fork again?

### ISSUE THREAD

**Issue by niccokunzmann** [spaceapi-community/my-hackerspace#41]
Hi, there does not seem to be progress here. Would it be better if I forked this one? I am also happy to become a mantainer just for progress. Dear maintainer, you forked it, tried to get the old app to point to yours and nothing was really improved. Please admit that you do not have much time for this. So, the question for me is: can I build on top of your work and get people involved to improve this? Or should I release a fork again, discarding your effort and taking up my time better spent on features?
I really like to see this move forward. Look at my repositories: I can mantain projects over years, tested, documented, open. If you do not like what I do here when I am a maintainer, just kick me out, reset master and tag a new release. Nobody gets hurt.
So, would it be ok if I get write access? Just to help out?
All the best, Nicco

**Comment by dbrgn** [comment]
Hi @niccokunzmann. To be honest, I forgot about the open PRs, so thanks for the reminder. (Updating this project is on my TODO-list anyways, since updating to the latest API level is required soon in order to keep the app in the Play store.)

However:

> Dear maintainer, you forked it, tried to get the old app to point to yours and nothing was really improved. Please admit that you do not have much time for this.

That is quite rude. If you look at the commit history, I spent quite some time in 2020-2022 to do the maintenance work of upgrading the app framework(s), getting the app to build again, fixing CI, paying for a new Google Play account, do the horrible work of submitting the app to Google Play (including coming up with all the required graphics), etc.

That kind of work is not really visible, the app still looks like before. But it was vital to keep the app alive. If people are now saying "you forked it (...) and nothing was really improved", that's quite demotivating.

Instead of saying "admit that you don't have time", how about writing a reminder about the open pull requests and just offering your help ("hey, some pull requests are still open, could you take a look? Do you need help with maintenance?")?

---

Anyways, I do appreciate help with maintenance. I am currently in the middle of packing and moving, but I will try to merge all open PRs in the coming days. I also intend to add you as a co-maintainer to this project. Something I think we should have though, to ensure good collaboration but to avoid the "maintainer is not responding" issue in the future, is some kind of "maintenance/governance guideline". I thought of something like this:

- List maintainers in the README
- Pull requests should ideally be reviewed by another team maintainer, but if nobody reacts within a week, PRs may be merged directly

I'll think about it some more. More suggestions are welcome as well.

**Comment by dbrgn** [comment]
Work done today:

- https://github.com/spaceapi-community/spaceapi-kt/pull/29
- https://github.com/spaceapi-community/spaceapi-kt/pull/28
- https://github.com/spaceapi-community/spaceapi-kt/pull/31
- https://github.com/spaceapi-community/spaceapi-kt/pull/32

(The old version of spaceapi-kt depends on kotlin-stdlib-jdk8 which causes conflicts when updating some other dependencies of MyHackerspace.)

**Comment by niccokunzmann** [comment]
@dbrgn Thanks for your answers. I admit: I flipped into a user perspective and just saw the features as work. Definitely: Making this app run again and updating the whole process and dependencies is valuable maintenance work that is often forgotten and behind the scenes. I am guilty of rushing to conclusions there, not taking that effort enough into consideration. 

> -    List maintainers in the README

 I want to create a PR for that, once I am added and I love documentation.

> -    Pull requests should ideally be reviewed by another team maintainer, but if nobody reacts within a week, PRs may be merged directly

Yes, I can submit to that process. Two weeks might be ok at the current pace.

**Comment by dbrgn** [comment]
Thanks for your fair reply 🙂 I can understand the frustration with slow maintenance, and having a low bus factor is a problem. After all, this is why spaceapi-community exists (if I don't respond anymore, other people can step in and add new maintainers).

I invited you to the spaceapi-community members. For discussions about future features and maintenance workflows, the Matrix chat (you're already part of it) is probably the best place.

For Google Play releases, ping me. I'd currently prefer to do that myself, but in the worst case, the other SpaceAPI core members have access to the Google Play credentials as well.
